### ISSUE TITLE
Pomap compilation breaks under 4.05+beta

### ISSUE THREAD

**Issue by gasche** [mmottl/pomap#2]
Because new functions were added to the standard library's Map module in 4.05, Pomap's compilation currently breaks. See the [opam-builder report](http://opam.ocamlpro.com/builder/html/pomap/pomap.3.0.6/78caa380c32b85e11b9e8e9dd93e569e):

```
File "lib/store_impl.ml", line 104, characters 24-29:
Error: Signature mismatch:
       ...
       In module Set:
       The value `find_last_opt' is required but not provided
       In module Set:
       The value `find_last' is required but not provided
       In module Set:
       The value `find_first_opt' is required but not provided
       In module Set:
       The value `find_first' is required but not provided
       In module Set:
       The value `find_opt' is required but not provided
       In module Set:
       The value `choose_opt' is required but not provided
       In module Set:
       The value `max_elt_opt' is required but not provided
       In module Set:
       The value `min_elt_opt' is required but not provided
```

I plan to change the metadata in the opam-repository to mark pomap 3.0.6 incompatible with 4.05, but you might want to release an updated version -- to enable your users to update to 4.05 around release time.

**Comment by mmottl** [comment]
Thanks for the report, I have updated the implementation to compile with OCaml 4.05.  Thanks, too, for updating related package constraints.
